-- AlterTable
ALTER TABLE "GameStatlines" ALTER COLUMN "fTPercent" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "threePointFGPercent" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "twoPointFGPercent" SET DATA TYPE DOUBLE PRECISION;
